### ISSUE TITLE
KeyError 'from_id'

### ISSUE THREAD

**Issue by aesto1** [yilbegan/vbio#3]
**Log:**
```
* [2019/May/04 18:16:43] INFO: Pooling started!
* [2019/May/04 18:16:48] ERROR: From message_new
Traceback (most recent call last):
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vbio\handlers\longpoll.py", line 46, in run
    self.bot.process_message(update['object'])
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vbio\bot.py", line 68, in process_message
    if msg.from_id in self.message_register_next_step:
  File "C:\Users\Evgeny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vbio\types.py", line 160, in __getattr__
    return self.data[item]
KeyError: 'from_id'
```
**Source code**
```
import vk_requests
# import emoji
from vbio import VkBot, LongPollClient

api = vk_requests.create_api(service_token='#')  # Токен ВКонтакте
bot = VkBot(api=api)
handler = LongPollClient(bot)
    
    
@bot.message_handler()
def hello_world(m):
    m.answer(message='Привет мир!')
    
    
if __name__ == '__main__':
    handler.run()
```

**Comment by aesto1** [comment]
**Ошибка была элементарной!
Попрошу добавить в readme уведомление что версия api должна быть 5,92!**
