### ISSUE TITLE
Ошибка после событий

### ISSUE THREAD

**Issue by Kotofey228** [yilbegan/vbio#5]
После каждого события в консоль выводится ошибка KeyError:
```
* [2019/Sep/09 01:39:31] ERROR: From message_typing_state
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/handlers/longpoll.py", line 51, in run
    self.bot.process_event(update['object'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/bot.py", line 91, in process_event
    req = VkEvent(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/types.py", line 248, in __init__
    self.type = data['type']
KeyError: 'type'
* [2019/Sep/09 01:39:32] INFO: Processed message from 49461083: Test
* [2019/Sep/09 01:39:32] ERROR: From message_reply
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/handlers/longpoll.py", line 51, in run
    self.bot.process_event(update['object'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/bot.py", line 91, in process_event
    req = VkEvent(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vbio/types.py", line 248, in __init__
    self.type = data['type']
KeyError: 'type'

```

**Comment by Kotofey228** [comment]
Нашел несоответствие:

_longpoll.py_
```
else:
                        self.bot.process_event(update)#['object'])
                        self.bot.logger.info('Processed event: {}'.format(update['type']))
```

_types.py_
```
class VkEvent:

    def __init__(self, data: dict):
        self.type = data['type']
        self.data = data['object']
        self.group_id = data['group_id']
```
В VkEvent приходит объект события вместо всего события, фиксится удалением ['object']
